apiVersion: v1
kind: Secret
metadata:
  name: k8-training
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  MONGO_ROOT_USERNAME: YWRtaW4K
  MONGO_ROOT_PASSWORD: cGFzc3dvcmQK
  MONGO_USERNAME: dHJhaW5pbmcK
  MONGO_PASSWORD: cGFzc3dvcmQK
  MONGO_USERS_LIST: YWRtaW4xOnVzZXJBZG1pbkFueURhdGFiYXNlLGRiQWRtaW5BbnlEYXRhYmFzZSxyZWFkV3JpdGVBbnlEYXRhYmFzZTpxYXpYU1dlZGMzMg==